#!/usr/bin/env bash
sudo apt-get install curl
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible
ansible-pull local.yml -U https://github.com/dzellio/ansible --ask-become-pass
