- hosts: localhost
  vars:
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/git-setup.yml
    - include: tasks/install-fonts.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/dotfiles-setup.yml
    - include: tasks/personal-projects.yml
    - include: tasks/brave-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/lsp-setup.yml

