- name: Cloning .files
  ansible.builtin.git:
    repo: 'https://github.com/dzellio/.files.git'
    dest: "{{ lookup('env', 'HOME') }}/.files"
  tags:
    - install
    - dotfiles
    - stow
- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
  become: true
- name: Stow dotfiles
  shell: cd $HOME/.files && ./ubuntu
  tags:
    - install
    - dotfiles
    - stow
